# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

default:
	GOOS=linux GOARCH=amd64 go build -o main
	zip soci_index_generator_lambda.zip main