// Add any unique troubleshooting steps here.
For troubleshooting common AWS Partner Solution issues, refer to the https://fwd.aws/rA69w?[AWS Quick Start General Information Guide] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation].

Lambda logs for generating SOCI Index artifacts can be found in the CloudWatch log group “`/aws/lambda/<StackName>-SociIndexGeneratorLambda`” and Lambda logs for repository image tag filtering and matches can be found in Cloudwatch Log Group “`/aws/lambda/<StackName>-ECRImageActionEventFilteringLambda`” where `<StackName>` is the name of the stack that you entered in the “Deployment steps” section.

If Lambda logs for generating SOCI Index Artifacts show that the Lambda function is timing out (e.g., you notice “Task timed out” in the log entry), this is likely caused by the size of image. SOCI Index Builder supports a maximum compressed image size of 6GB, because larger sizes may result in the SOCI Index Builder Lambda timing out after 15 minutes.

== Resources

AWS Services:

* https://aws.amazon.com/cloudformation/[AWS Cloudformation]
* https://aws.amazon.com/eventbridge/[AWS EventBridge]
* https://aws.amazon.com/lambda/[AWS Lambda]
* https://aws.amazon.com/s3/[AWS S3]
* https://aws.amazon.com/ecr/[AWS ECR]
* https://aws.amazon.com/cloudwatch/[AWS Cloudwatch]

